<definitions name="StandardGetServiceService"
             targetNamespace="#{host}#{root}/wsdl/StandardGetService.wsdl"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="#{host}#{root}/wsdl/StandardGetService.wsdl"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <message name="StandardGetServiceRequest">
        <part name="firstName" type="xsd:string"/>
    </message>

    <message name="StandardGetServiceResponse">
        <part name="greeting" type="xsd:string"/>
    </message>

    <portType name="StandardGetService_PortType">
        <operation name="StandardGetService">
            <input message="tns:StandardGetServiceRequest"/>
            <output message="tns:StandardGetServiceResponse"/>
        </operation>
    </portType>

    <binding name="StandardGetService_Binding" type="tns:StandardGetService_PortType">
        <soap:binding style="rpc"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="StandardGetService">
            <soap:operation soapAction="StandardGetService"/>
            <input>
                <soap:body
                        encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                        namespace="urn:examples:standardgetservice"
                        use="encoded"/>
            </input>

            <output>
                <soap:body
                        encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                        namespace="urn:examples:standardgetservice"
                        use="encoded"/>
            </output>
        </operation>
    </binding>

    <service name="StandardGetService_Service">
        <documentation>WSDL File for StandardGetServiceService</documentation>
        <port binding="tns:StandardGetService_Binding" name="StandardGetService_Port">
            <soap:address
                    location="#{host}#{root}/StandardGetService"/>
        </port>
    </service>
</definitions>